### ISSUE TITLE
Bro Can I have one HacktoberFest's Tshirt ? 

### ISSUE THREAD

**Issue by ansh-ptel** [dhruvikn/Problem-Solving---Algorithms-Collection#17]

**Comment by ansh-ptel** [comment]
Kapde Nahi he bhai ab

**Comment by dhruvikn** [comment]
Nahi bhai sorry. Sab already reserved h for family. 😂

**Comment by itspriyansh** [comment]
Bhai meko bhi please 😂😂

**Comment by dhruvikn** [comment]
This topic is no longer open for discussion Mr. @priyanshu29470
